config/routes.rb
Rails.application.routes.draw do
  get 'search/show'
  get 'celebrities/index'
  devise_for :users
  root to: 'celebrities#landing'

 resources :celebrities, only: [:index, :show] do
    resources :bookings, only: [:create]
    resources :wishlists, only: [:create, :destroy]
    resources :celebrity_tags, only: [:new, :create]
  end

  resources :bookings, only: [:index, :edit, :update, :destroy]
  resources :users, only: :update
  resources :wishlists, only: [:index]

  delete '/wishlist/:id', to:'wishlists#destroy_wishlists', as: 'wishlist'

  get '/landing', to: 'celebrities#landing'

  get '/my-profile', to: 'users#show'
  get 'edit-profile/:id/form', to: 'users#edit', as: 'edit_profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :celebrity
  BOOKING_STATUS = ['Accepted', 'Pending', 'Cancelled', 'Completed'].freeze
  validates :status, inclusion: { in: BOOKING_STATUS }
  validates :status, :duration, :rate_per_hour, presence: true
  validates :rate_per_hour, numericality: { only_integer: true }
  validates :rate_per_hour, numericality: { greater_than_or_equal_to: 1 }
  validates :duration, numericality: { only_integer: true }
end

app/models/celebrity.rb
class Celebrity < ApplicationRecord
  include PgSearch
  pg_search_scope :search_by_firs_name_and_last_name_and_description,
                  against: [:last_name, :first_name, :description],
                  using: {
                    tsearch: { prefix: true } # <-- now `superman batm` will return something!
                  }

  has_many :bookings
  has_many :celebrity_tags
  has_many :tags, through: :celebrity_tags

  validates :first_name, :last_name, presence: true
  validates :last_name, uniqueness: { scope: :first_name }
  validates :photo, :description, :rate_per_hour, :date_of_birth, :gender, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def location
    "#{city}, #{country}"
  end

  private

  def will_save_change_to_location?
    will_save_change_to_city? || will_save_change_to_country?
  end
end

app/models/celebrity_tag.rb
class CelebrityTag < ApplicationRecord
  belongs_to :celebrity
  belongs_to :tag

  validates :tag, uniqueness: {
                                scope: :celebrity,
                                message: 'has already been added'
                              }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :celebrity_tags, dependent: :destroy
  has_many :celebrities, through: :celebrity_tags

  validates :name, presence: true, uniqueness: { insensitive: true }

  def self.list_names
    pluck(:name).map(&:capitalize).sort
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :bookings, dependent: :destroy
  has_many :celebrities, through: :bookings
  has_many :wishlists, dependent: :destroy
  has_many :celebrities, through: :whishlists
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # validates :first_name, :last_name, :date_of_birth, presence: true

  def wishlisted_celebrity?(celebrity)
    wishlists.where(celebrity: celebrity).any?
  end
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  belongs_to :celebrity
  validates :user_id, :celebrity_id, presence: true
  # validates :user_id, uniqueness: { scope: :celebrity_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:edit, :update, :destroy]
  before_action :set_celebrity, only: :create

  def index
    @bookings = current_user.bookings
    @wishlists = current_user.wishlists
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.celebrity = @celebrity
    @booking.rate_per_hour = @celebrity.rate_per_hour
    @booking.user = current_user
    @booking.status = 'Pending'
    if @booking.save
      redirect_to bookings_path
    else
      render 'celebrities/show'
    end
  end

  def edit
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to bookings_path
    else
      render :edit
    end
  end

  def destroy
    @bookings.update(status: 'Cancelled')

    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:status, :duration, :rate_per_hour, :user_id, :celebrity_id, :booking_date)
  end

  def set_booking
    @bookings = Booking.find(params[:id])
  end

  def set_celebrity
    @celebrity = Celebrity.find(params[:celebrity_id])
  end
end

app/controllers/celebrities_controller.rb
class CelebritiesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show landing]

  def index
    @celebrities = Celebrity.where.not(latitude: nil, longitude: nil)

    if params[:query].present?
      @celebrities = @celebrities.search_by_firs_name_and_last_name_and_description(params[:query])
    end
    add_celebrity_markers
  end

  def show
    @celebrities = Celebrity.where.not(latitude: nil, longitude: nil)
    @celebrity = @celebrities.find(params[:id])
    @booking = Booking.new(rate_per_hour: @celebrity.rate_per_hour)

    create_destroy_wishlist(@celebrity)

    @markers = [
      {
        lat: @celebrity.latitude,
        lng: @celebrity.longitude
      }
    ]
  end

  def landing
    @celebrities = Celebrity.order('RANDOM()').first(4)
  end

  private

  def create_destroy_wishlist(celebrity)
    if current_user.wishlisted_celebrity?(celebrity)
      @wishlist = current_user.wishlists.find_by(celebrity: params[:id])
    else
      @wishlist = Wishlist.new
    end
  end

  def add_celebrity_markers
    @markers = @celebrities.map do |celebrity|
      {
        lat: celebrity.latitude,
        lng: celebrity.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { celebrity: celebrity })
      }
    end
  end
end

app/controllers/celebrity_tags_controller.rb
class CelebrityTagsController < ApplicationController
  before_action :set_celebrity

  def new
    @celebrity_tag = CelebrityTag.new
  end

  def create
    names = params[:celebrity_tag][:tag].reject(&:empty?).map(&:downcase)
    names.each do |name|
      tag = Tag.find_or_create_by(name: name)
      CelebrityTag.create(celebrity: @celebrity, tag: tag)
    end
    redirect_to @celebrity
  end

  private

  def set_celebrity
    @celebrity = Celebrity.find(params[:celebrity_id])
  end
end

app/controllers/celebrties_controller.rb
class CelebrtiesController < ApplicationController
  def index
    @celebrties = Celebrity.all
  end

  def show
    @celebrity = Celebrity.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to celebrities_path
    else
      render :new
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)

    redirect_to my_profile_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :date_of_birth, :gender,:photo)
  end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :set_celebrity, only: %i[create destroy]
  def index
    @wishlists = current_user.wishlists
    @celebrity = Celebrity.all.order('RANDOM()').first
  end

  def create
    @wishlist = Wishlist.new
    @wishlist.celebrity = @celebrity
    @wishlist.user = current_user
    @wishlist.save

    redirect_to celebrity_path(@celebrity)

    # add AJAX
  end

  def destroy
    @wishlist = Wishlist.find(params[:id])
    @wishlist.destroy

    redirect_to celebrity_path(@celebrity)
    # redirect_to request.referer

    # add AJAX
  end

  def destroy_wishlists
    @wishlist = Wishlist.find(params[:id])
    @wishlist.destroy

    redirect_to wishlists_path
  end

  private

  def set_celebrity
    @celebrity = Celebrity.find(params[:celebrity_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="form-category">
  <%= simple_form_for [@celebrity, @booking] do |f| %>
    <h3>Rate per hour:</h3> <h2><%= number_to_currency(@celebrity.rate_per_hour) %></h2>
    <%= f.input :duration %>
    <%= f.input :booking_date, as: :string, required: false, input_html: {class: "datepicker"} %>
    <%= f.submit %>
  <% end %>
</div>

app/views/bookings/_update.html.erb
<%= simple_form_for (booking)  do |f| %>
  <div class="">
    <p>Duration:</p>
    <%= f.input :duration, label: false, collection: 1..10 %>
  </div>
  <div>
    <p>Date:</p>
  <%= f.input :booking_date, as: :string, required: false, label: false,defaultDate: booking.booking_date, input_html: {class: "datepicker"} %></div>

  <%= f.button :submit, 'Update', data: {confirm: "You about to change your booking with #{booking.celebrity.first_name}. Are you sure you're ready to do this?"}, class: 'btn btn-link' %>
<% end %>

app/views/bookings/edit.html.erb
<h1>Cancel booking</h1>
<%= simple_form_for(@bookings) do |b| %>
<%= b.input :status, input_html: { value: 'Cancelled' } %>
<%= b.submit 'Cancel', class: 'btn btn-primary' %>
<% end %>

app/views/bookings/index.html.erb
<br>

<div class="booking-header">
  <h1 style="color: white;">Bookings for <%= current_user.first_name %> </h1>
</div>
<br>
<div class="container">
  <% @bookings.each do |booking| %>
    <% if booking.status != 'Cancelled' %>
      <div class="booking-product">
        <div class="booking-photo">
          <%= image_tag(booking.celebrity.photo, class: "avatar") %>
        </div>
        <div class="card-booking-infos">
          <div class="card-booking-name">
            <%= link_to booking.celebrity.full_name, celebrity_path(booking.celebrity), class: "btn btn-link update-btn"%>
          </div>
          <div class="booking-status-div">
            <%= render 'bookings/update', booking: booking %></p>
          </div>
          <div class='card-rate-infos'>
            <p>Status: <strong><%= booking.status %></strong></p>
            <p>Rate per hour: <strong>$<%= booking.rate_per_hour %></strong></p>
            <p>Total: <strong>$<%=booking.duration*booking.rate_per_hour %></strong></p>
          </div>
        </div>

        <div class="card-booking-buttons">
          <%= link_to "Cancel booking", booking_path(booking), method: :delete, data: { confirm: "You are ditching #{booking.celebrity.first_name}...are you sure about this?" }, class: 'btn btn-link' %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/celebrities/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1549045872-0da5eb6316a2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2980&q=80);">
  <div class="container">
    <div class="content">
      <div class="content__container">
        <p class="content__container__text">Hang out with
          <span id="banner-typed-text"
            data-celebrities="<%= @celebrities.map(&:first_name).to_json %>"
          >John</span>
        </p>


      </div>
      <h5 class="text-center" id="banner-slogan">Once in a lifetime experience to spend time with your favorite celebrity</h5>
    </div>
    <!-- <div class="container mb-4">
      <h1>Celebrent revolutionize the way of making friends, <strong>hanging out with a celebrity is not a dream anymore! </strong>!</h1>
      <% if user_signed_in? == false %>
        <%= link_to 'Sign up now', new_user_registration_path, class: "btn btn-secondary mt-3" %>
      <% end %>
    </div> -->
  </div>
</div>

app/views/celebrities/_carousal.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <% @celebrities.each_with_index do |celebrity, index| %>
    <div class="carousel-item #{'active' if i == 0} ">
      <%= image_tag(celebrity.photo, class: "d-block w-100") %>
    </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/celebrities/_celebrity.html.erb
<div class="card">
  <%= image_tag(celebrity.photo, class: "card-img-top card-img-size")%>
  <div class="card-body">
    <h5 class="card-title"><%= celebrity.full_name %></h5>
    <p class="card-text"><%= celebrity.description %></p>
    <p class="card-text"><i class="fas fa-dollar-sign"></i> <%= celebrity.rate_per_hour %> /per hour</p>
    <%= link_to 'Book Now', celebrity_path(celebrity), class: "btn btn-secondary" %>
    <p class="card-text"><small class="text-muted">Last booked <%= rand(1..10) %> mins ago</small></p>
  </div>
</div>

app/views/celebrities/_footer.html.erb
<footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <h6>About</h6>
            <p class="text-justify">Celebrent.com <i>RENTING CELEBRITIES CAN BE SIMPLE </i> We want everyone with $$, spend your money on something that's worth it. </p>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Categories</h6>
            <ul class="footer-links">
              <li><a href="http://scanfcode.com/category/c-language/">Actor/Actress</a></li>
              <li><a href="http://scanfcode.com/category/front-end-development/">Politician</a></li>
              <li><a href="http://scanfcode.com/category/back-end-development/">Singer</a></li>
              <li><a href="http://scanfcode.com/category/java-programming-language/">DJ</a></li>
              <li><a href="http://scanfcode.com/category/android/">Artist</a></li>
              <li><a href="http://scanfcode.com/category/templates/">Infulencer</a></li>
            </ul>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Quick Links</h6>
            <ul class="footer-links">
              <li><a href="http://scanfcode.com/about/">About Us</a></li>
              <li><a href="http://scanfcode.com/contact/">Contact Us</a></li>
              <li><a href="http://scanfcode.com/contribute-at-scanfcode/">Contribute</a></li>
              <li><a href="http://scanfcode.com/privacy-policy/">Privacy Policy</a></li>
              <li><a href="http://scanfcode.com/sitemap/">Sitemap</a></li>
            </ul>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyright &copy; 2017 All Rights Reserved by
         <a href="#">Celebrent</a>.
            </p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="#"><i class="fab fa-facebook"></i></a></li>
              <li><a class="twitter" href="#"><i class="fab fa-twitter"></i></a></li>
              <li><a class="dribbble" href="#"><i class="fab fa-dribbble"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fab fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
</footer>

app/views/celebrities/_heart.html.erb
<% if current_user.wishlisted_celebrity?(@celebrity) %>
  <%= link_to celebrity_wishlist_path(celebrity_id: @celebrity, id: @wishlist), controlller: :wishlists, method: :delete do %><i class="fas fa-heart black"></i><% end %>
<% else %>
  <%= link_to celebrity_wishlists_path(@celebrity), method: :post do %><i class="far fa-heart black"></i><% end %>
<% end %>

app/views/celebrities/_infowindow.html.erb
<div class="card" style="border:none; background-color:transparent; box-shadow:none;">
  <div class="card-body" style="padding: 0px;">
    <div class="marker-photo" style="display: flex; justify-content: center;">
    <%= image_tag(celebrity.photo, class: "avatar") %>
    </div>
    <div class="marker-info ml-3">
      <h6><%= link_to celebrity.full_name,celebrity_path(celebrity), {style: 'color: black'} %></h6>
    </div>
  </div>
</div>

app/views/celebrities/index.html.erb
<% if @celebrities.any? %>
  <div class="main">
    <div class="container-show-b">
    <div
      id="map"
      style="width: 100%;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key=<%= ENV['MAPBOX_API_KEY'] %>
    ></div>
  </div>
    <div class="cards">
      <% @celebrities.each do |celebrity| %>
      <div class="card">
        <%= image_tag(celebrity.photo, class: "card-img") %>


        <div class="card-trip-infos">
          <div>
            <h2><%= celebrity.full_name %></h2>
            <p><%= celebrity.description %></p>
          </div>
          <h2 class="card-trip-pricing">$<%= celebrity.rate_per_hour %></h2>
          <!-- <img src='https://kitt.lewagon.com/placeholder/users/krokrob' class="card-trip-user avatar-bordered"/> -->
        </div>
        <button type="button" class="btn btn-secondary">
          <%= link_to "Book me!", celebrity_path(celebrity["id"])%></button>
      </div>
      <% end %>
    </div>
  </div>

</div>
<% else %>
  <div class="no-results">
    <p>Oops, No Results Found</p>
  </div>
<% end %>

app/views/celebrities/landing.html.erb
<%= render 'banner' %>
<div class="pb-4">
  <div class="container">
    <div class="neon"><p class="outline text-center">
      CELEBRITIES FOR RENT</p>
    </div>
    <div class="card-deck">
      <%= render @celebrities %>
    </div>
  </div>
</div>
<%= render 'footer' %>

app/views/celebrities/show.html.erb
<br>
<br>
<div class="container-show">
  <div class="container-photo">
    <%= image_tag(@celebrity.photo, class: "img-show" ) %>
  </div>


  <div class="container-info-text">
    <h3><%= @celebrity.full_name %>
      <!-- make a div for heart -->
      <% if current_user.wishlisted_celebrity?(@celebrity) %>
        <%= link_to celebrity_wishlist_path(celebrity_id: @celebrity, id: @wishlist), controlller: :wishlists, method: :delete do %><i class="fas fa-heart black"></i><% end %>
      <% else %>
      <%= link_to celebrity_wishlists_path(@celebrity), method: :post do %><i class="far fa-heart black"></i><% end %>
      <% end %>
    </h3>
    <br>
    <p><%= @celebrity.gender %></p>
    <p><%= @celebrity.date_of_birth.strftime("%F") %></p>

    <div class="tags-container">
      <% @celebrity.tags.each do |tag| %>
        <div class="celebrity-tags">
          <h5><span class="badge badge-secondary"><%= tag.name %></span></h5>
        </div>
      <% end %>
      <div class="celebrity-tags">
        <div class="badge badge-warning" >
          <%= link_to new_celebrity_celebrity_tag_path(@celebrity) do %>
            <i class='fas fa-plus-circle'></i> Tag
          <% end %>
        </div>
      </div>
    </div>

    <%= render 'bookings/form', booking: @booking%>

  </div>
  <div class="container-map">
    <div
      id="map"
      style="width: 400px;
      box-shadow: 0 0 4px rgba(0, 0, 0, 0.2);
      height: 565px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key=<%= ENV['MAPBOX_API_KEY'] %>
    ></div>
  </div>

</div>

app/views/celebrity_tags/new.html.erb
<h1>Add tags to <%= @celebrity.full_name %></h1>
<div class="row">
  <div class="col-sm-6">
    <%= simple_form_for [@celebrity, @celebrity_tag] do |f| %>
      <%= f.input :tag, collection: Tag.list_names,
                  include_blank: false,
                  include_hidden: false,
                  input_html: { multiple: true }
      %>

      <%= f.button :submit, 'Save', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Celebrent</title>
    <link href='https://fonts.googleapis.com/css?family=Arvo:700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Raleway:300,100' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body style="background-color: rgb(25,25,26);">
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to 'CELEBRENT', landing_path, class: "navbar-brand-text-light" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%= form_tag celebrities_path, method: :get do %>
      <%= text_field_tag :query,
          params[:query],
          class: "form-control mr-2",
          placeholder: "Find a celebrity"
      %>
      <% end %>
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to "Bookings", bookings_path, class: " btn-outline-light btn mx-2" %>
      </li>
      <li class="nav-item dropdown">
        <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Profile", my_profile_path, class: "dropdown-item" %>
          <%= link_to "Wishlist", wishlists_path, class: "dropdown-item" %>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
    <% else %>
      <li class="nav-item active">
      <%= link_to 'Login', user_session_path, class: 'nav-link btn btn-light' %>
        </li>
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :first_name %>
  </div>

  <div class="form-inputs">
    <%= f.input :last_name %>
  </div>

  <div class="form-inputs">
    <%= f.input :date_of_birth, start_year: Date.today.year - 100, end_year: Date.today.year %>
  </div>

  <div class="form-inputs">
    <%= f.input :gender %>
  </div>
  <div class="form-actions">
    <%= f.input :photo %>
  </div>
    <%= f.input :photo_cache, as: :hidden %>
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>


<% end %>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h1>hello, <%= @user.first_name%></h1>

<ul>
  <li><p><%= @user.first_name %> <%= @user.last_name %></p></li>
  <li><p><%= @user.gender %></p></li>
  <li><p><%= @user.date_of_birth %></p></li>
  <li><p><%= @user.email %></p></li>
</ul>

<%= link_to 'Edit profile', edit_profile_path(@user), class: 'btn btn-primary' %>
<%= link_to 'Current bookings', bookings_path, class: 'btn btn-primary' %>

app/views/wishlists/_card.html.erb
  <div class="card-wishlists wishlist-cards">
    <div class="username-card">
      <h2>Wish List for</h2>
      <h3><%= current_user.first_name %> 🔥</h3>
    </div>
      <% @wishlists.each do |wishlist| %>
      <div class="card-wishlist d-flex">
        <%= image_tag(wishlist.celebrity.photo)  %>
        <div class="card-wishlist-infos">
          <h2><%= wishlist.celebrity.full_name %></h2>
          <p><strong><%= wishlist.celebrity.description %></strong></p>
          <%= link_to "book now", celebrity_path(wishlist.celebrity),class: "btn btn-light btn-sm mt-2" %>
        </div>
        <div class="delete-button">
          <%= link_to wishlist_path(wishlist), method: :delete, style: 'color:black;' do %>
            <i class="fas fa-times-circle"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

app/views/wishlists/index.html.erb
<div class="mt-3">
  <div class="wishlist-content d-flex">
    <%= render 'card' %>
    <div class="wishlist-ad">
      <div class="card">
          <div class="promo">
            <p class="mt-3">Sale</p>
          </div>
          <%= image_tag(@celebrity.photo, class: "card-img") %>
          <div class="card-trip-infos">
            <div>
              <h2><%= @celebrity.full_name %></h2>
              <p><%= @celebrity.description %></p>
            </div>
            <h2 class="card-trip-pricing mr-0">$<%= @celebrity.rate_per_hour - 10 %>
            <h2 class="card-trip-pricing line-through">$<%= @celebrity.rate_per_hour %></h2>
          </div>
          <button type="button" class="btn btn-secondary">
            <%= link_to "Book me!", celebrity_path(@celebrity)%></button>
        </div>
      </div>
    </div>
  </div>
</div>